version: 2.0.0.{build}

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
- ps: .\src\build.ps1 -Configuration Release

test_script:
- ps: .\src\UniversalDashboard.UITest\shebang.tests.ps1 -Release -Integration

artifacts:
- path: src/output